# Generated by Django 3.0.6 on 2020-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailblazr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='location',
            field=models.CharField(default='', max_length=222),
        ),
        migrations.AddField(
            model_name='trail',
            name='lon',
            field=models.IntegerField(default=0),
        ),
    ]
