# Generated by Django 3.0.6 on 2020-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailblazr', '0002_auto_20200508_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
